[workspace]
authors = ["sanjaysgk <44039457+sanjaysgk@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "ipg"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25.10.4,<26"
nf-core = ">=3.5.2,<4"
nf-test = ">=0.9.5,<0.10"
pre-commit = ">=4.5.1,<5"
prettier = ">=3.8.1,<4"
shellcheck = ">=0.11.0,<0.12"
gh = ">=2.88.1,<3"
openjdk = "17.*"
samtools = ">=1.23.1,<2"
bcftools = ">=1.23.1,<2"
seqtk = ">=1.5,<2"
star = ">=2.7.11b,<3"
