contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #ipg channel"
    url: https://nfcore.slack.com/channels/ipg
    about: Discussion about the sanjaysgk/ipg pipeline
